tap "homebrew/autoupdate"
tap "homebrew/bundle"
brew "coreutils"
brew "direnv"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "git-lfs"
brew "mtr"
brew "rsync"
brew "watch"
brew "wget"
brew "zsh"
brew "mise"
# these are for node-gyp to build sharp
brew "pixman"
brew "pkg-config"
brew "pango"
# end node-gyp for sharp
cask "orbstack"
cask "visual-studio-code"
cask "iterm2"
