#!/usr/bin/env bash
# =============================================================================
# optimise-vps.sh — Ubuntu Server optimisation for shared 2-CPU Zen VPS
# Usage: sudo bash optimise-vps.sh [--dry-run]
# =============================================================================

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
ok()      { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
section() { echo -e "\n${BOLD}${CYAN}━━━  $*  ━━━${RESET}"; }

# ── Dry-run mode ──────────────────────────────────────────────────────────────
DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

run() {
  if $DRY_RUN; then
    echo -e "  ${YELLOW}[DRY-RUN]${RESET} $*"
  else
    eval "$@"
  fi
}

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  error "This script must be run as root (sudo bash $0)"
  exit 1
fi

# ── OS check ──────────────────────────────────────────────────────────────────
if ! grep -qi "ubuntu" /etc/os-release 2>/dev/null; then
  warn "This script targets Ubuntu. Detected OS may differ — proceed with caution."
fi

# ── Backup directory ──────────────────────────────────────────────────────────
BACKUP_DIR="/root/vps-optimise-backup-$(date +%Y%m%d-%H%M%S)"
if ! $DRY_RUN; then
  mkdir -p "$BACKUP_DIR"
  info "Backups will be saved to: $BACKUP_DIR"
fi

backup_file() {
  local file="$1"
  if [[ -f "$file" ]] && ! $DRY_RUN; then
    cp -a "$file" "$BACKUP_DIR/$(basename "$file").bak" 2>/dev/null || true
  fi
}

# ── Summary tracking ──────────────────────────────────────────────────────────
CHANGES=()
SKIPPED=()
WARNINGS=()

log_change()  { CHANGES+=("$*"); }
log_skipped() { SKIPPED+=("$*"); }
log_warn()    { WARNINGS+=("$*"); }

# =============================================================================
section "1 · System Update & Package Cleanup"
# =============================================================================

info "Updating package lists..."
run "apt-get update -qq"

info "Removing known bloat packages (safe to remove on a headless server)..."
BLOAT_PKGS=(snapd whoopsie apport postfix popularity-contest)
for pkg in "${BLOAT_PKGS[@]}"; do
  if dpkg -l "$pkg" &>/dev/null 2>&1; then
    run "apt-get purge -y $pkg 2>/dev/null || true"
    log_change "Purged: $pkg"
  else
    log_skipped "Not installed: $pkg"
  fi
done

run "apt-get autoremove --purge -y -qq"
ok "Package cleanup done"

# =============================================================================
section "2 · Disable Unnecessary Services"
# =============================================================================

SERVICES_TO_DISABLE=(
  bluetooth cups avahi-daemon
  ModemManager wpa_supplicant
  multipathd iscsid
)

for svc in "${SERVICES_TO_DISABLE[@]}"; do
  if systemctl list-unit-files "${svc}.service" &>/dev/null 2>&1 | grep -q "$svc"; then
    run "systemctl disable --now $svc 2>/dev/null || true"
    log_change "Disabled service: $svc"
  else
    log_skipped "Service not found: $svc"
  fi
done
ok "Service cleanup done"

# =============================================================================
section "3 · Kernel / sysctl Tuning"
# =============================================================================

SYSCTL_FILE="/etc/sysctl.d/99-vps-optimise.conf"
backup_file "$SYSCTL_FILE"

info "Writing sysctl tuning parameters to $SYSCTL_FILE..."
run "cat > $SYSCTL_FILE << 'SYSCTL'
# ── VPS Optimisation (generated by optimise-vps.sh) ──────────────────────────

# Memory
vm.swappiness                    = 10
vm.vfs_cache_pressure            = 50
vm.dirty_ratio                   = 15
vm.dirty_background_ratio        = 5

# Network — BBR congestion control + FQ qdisc
net.core.default_qdisc           = fq
net.ipv4.tcp_congestion_control  = bbr

# Socket buffers
net.core.rmem_max                = 16777216
net.core.wmem_max                = 16777216
net.ipv4.tcp_rmem                = 4096 87380 16777216
net.ipv4.tcp_wmem                = 4096 65536 16777216

# Connection handling
net.ipv4.tcp_fastopen            = 3
net.core.somaxconn               = 65535
net.ipv4.tcp_max_syn_backlog     = 8192
net.ipv4.tcp_fin_timeout         = 15
net.ipv4.tcp_keepalive_time      = 300
net.ipv4.tcp_keepalive_intvl     = 30
net.ipv4.tcp_keepalive_probes    = 5

# Harden a little (safe for most workloads)
net.ipv4.conf.all.rp_filter      = 1
net.ipv4.tcp_syncookies          = 1

# File descriptors
fs.file-max                      = 2097152
SYSCTL"

run "sysctl --system -q"
log_change "Applied sysctl tuning ($SYSCTL_FILE)"

# Verify BBR loaded
if ! $DRY_RUN; then
  CURRENT_CC=$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo "unknown")
  if [[ "$CURRENT_CC" == "bbr" ]]; then
    ok "BBR congestion control is active"
  else
    warn "BBR not active (current: $CURRENT_CC) — kernel may not support it"
    log_warn "BBR not activated; current cc: $CURRENT_CC"
  fi
fi

# =============================================================================
section "4 · I/O Scheduler"
# =============================================================================

UDEV_RULE="/etc/udev/rules.d/60-io-scheduler.rules"
backup_file "$UDEV_RULE"

info "Setting I/O scheduler to 'none' for SSD/NVMe-backed virtual disks..."
run "cat > $UDEV_RULE << 'UDEV'
# Prefer 'none' for virtualised NVMe/SSD; mq-deadline for rotational
ACTION==\"add|change\", KERNEL==\"nvme[0-9]*\",       ATTR{queue/scheduler}=\"none\"
ACTION==\"add|change\", KERNEL==\"sd[a-z]|vd[a-z]\",  ATTR{queue/scheduler}=\"none\"
UDEV"

# Apply immediately to all detected block devices
if ! $DRY_RUN; then
  for dev in /sys/block/*/queue/scheduler; do
    blk=$(echo "$dev" | cut -d/ -f4)
    scheduler_path="/sys/block/${blk}/queue/scheduler"
    rotational_path="/sys/block/${blk}/queue/rotational"
    [[ -f "$rotational_path" ]] && rot=$(cat "$rotational_path") || rot=0
    if [[ "$rot" == "0" && -f "$scheduler_path" ]]; then
      echo none > "$scheduler_path" 2>/dev/null && \
        log_change "I/O scheduler → none for /dev/$blk" || \
        log_warn "Could not set scheduler for /dev/$blk (may be locked by hypervisor)"
    fi
  done
fi
ok "I/O scheduler udev rule written"

# =============================================================================
section "5 · Memory — Transparent Huge Pages"
# =============================================================================

THP_PATH="/sys/kernel/mm/transparent_hugepage/enabled"
if [[ -f "$THP_PATH" ]]; then
  run "echo madvise > $THP_PATH"
  # Persist across reboots via rc.local / systemd drop-in
  THP_SERVICE="/etc/systemd/system/thp-madvise.service"
  run "cat > $THP_SERVICE << 'SVC'
[Unit]
Description=Set THP to madvise (Zen VPS optimisation)
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
SVC"
  run "systemctl daemon-reload && systemctl enable --now thp-madvise.service 2>/dev/null"
  log_change "THP set to madvise (balanced for Zen)"
else
  log_skipped "THP sysfs path not found (likely a container)"
fi

# =============================================================================
section "6 · zRAM (compressed swap in RAM)"
# =============================================================================

TOTAL_RAM_MB=$(awk '/MemTotal/ {printf "%d", $2/1024}' /proc/meminfo)
info "Detected RAM: ${TOTAL_RAM_MB} MB"

if [[ "$TOTAL_RAM_MB" -le 2048 ]]; then
  info "Low RAM detected — installing zram-tools..."
  run "apt-get install -y -qq zram-tools"
  ZRAM_CONF="/etc/default/zramswap"
  backup_file "$ZRAM_CONF"
  run "cat > $ZRAM_CONF << 'ZRAM'
ALGO=lz4
PERCENT=50
ZRAM"
  run "systemctl restart zramswap 2>/dev/null || true"
  log_change "zRAM enabled (lz4, 50% of RAM)"
else
  info "RAM ≥ 2 GB — skipping zRAM (not required)"
  log_skipped "zRAM (sufficient RAM: ${TOTAL_RAM_MB} MB)"
fi

# =============================================================================
section "7 · File & Process Limits"
# =============================================================================

LIMITS_FILE="/etc/security/limits.d/99-vps.conf"
backup_file "$LIMITS_FILE"

run "cat > $LIMITS_FILE << 'LIMITS'
# VPS optimisation — raised file descriptor & process limits
*    soft  nofile  65535
*    hard  nofile  65535
*    soft  nproc   32768
*    hard  nproc   32768
root soft  nofile  65535
root hard  nofile  65535
LIMITS"

# systemd service limit
SYSTEMD_CONF="/etc/systemd/system.conf.d/99-limits.conf"
run "mkdir -p /etc/systemd/system.conf.d"
run "cat > $SYSTEMD_CONF << 'SYSD'
[Manager]
DefaultLimitNOFILE=65535
DefaultLimitNPROC=32768
SYSD"
run "systemctl daemon-reexec 2>/dev/null || true"
log_change "Raised file/process limits (PAM + systemd)"

# =============================================================================
section "8 · journald Log Size"
# =============================================================================

JOURNALD_CONF="/etc/systemd/journald.conf.d/99-size.conf"
run "mkdir -p /etc/systemd/journald.conf.d"
backup_file "$JOURNALD_CONF"
run "cat > $JOURNALD_CONF << 'JOURNALD'
[Journal]
SystemMaxUse=100M
RuntimeMaxUse=50M
MaxRetentionSec=2week
JOURNALD"
run "systemctl restart systemd-journald 2>/dev/null || true"
log_change "journald capped at 100 MB / 2 weeks"

# =============================================================================
section "9 · Install Lightweight Monitoring Tools"
# =============================================================================

TOOLS=(htop iotop nethogs ncdu)
for tool in "${TOOLS[@]}"; do
  if ! command -v "$tool" &>/dev/null; then
    run "apt-get install -y -qq $tool"
    log_change "Installed: $tool"
  else
    log_skipped "Already installed: $tool"
  fi
done

# =============================================================================
section "10 · CPU Governor (best-effort)"
# =============================================================================

GOV_PATH="/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
if [[ -f "$GOV_PATH" ]]; then
  CURRENT_GOV=$(cat "$GOV_PATH")
  if [[ "$CURRENT_GOV" != "schedutil" ]]; then
    run "echo schedutil | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor > /dev/null 2>&1 || true"
    log_change "CPU governor set to schedutil (was: $CURRENT_GOV)"
  else
    log_skipped "CPU governor already schedutil"
  fi
else
  warn "CPU frequency scaling not exposed by hypervisor — skipping"
  log_skipped "CPU governor (not available in this VPS)"
fi

# =============================================================================
section "11 · Disable tmpfs Mounts"
# =============================================================================

info "Masking unnecessary tmpfs mounts via systemd..."
TMPFS_UNITS=(tmp.mount)

for unit in "${TMPFS_UNITS[@]}"; do
  if systemctl list-unit-files "$unit" &>/dev/null 2>&1 | grep -q "$unit"; then
    if systemctl is-active --quiet "$unit" 2>/dev/null; then
      run "systemctl stop $unit 2>/dev/null || true"
    fi
    run "systemctl mask $unit 2>/dev/null || true"
    log_change "Masked tmpfs unit: $unit"
  else
    log_skipped "tmpfs unit not found: $unit"
  fi
done
ok "tmpfs mounts disabled"

# =============================================================================
#  SUMMARY
# =============================================================================
echo ""
echo -e "${BOLD}${GREEN}══════════════════════════════════════════${RESET}"
echo -e "${BOLD}${GREEN}  Optimisation Complete!${RESET}"
echo -e "${BOLD}${GREEN}══════════════════════════════════════════${RESET}"

if [[ ${#CHANGES[@]} -gt 0 ]]; then
  echo -e "\n${GREEN}✔ Applied (${#CHANGES[@]}):${RESET}"
  for c in "${CHANGES[@]}"; do echo "    • $c"; done
fi

if [[ ${#SKIPPED[@]} -gt 0 ]]; then
  echo -e "\n${CYAN}⊘ Skipped (${#SKIPPED[@]}):${RESET}"
  for s in "${SKIPPED[@]}"; do echo "    • $s"; done
fi

if [[ ${#WARNINGS[@]} -gt 0 ]]; then
  echo -e "\n${YELLOW}⚠ Warnings (${#WARNINGS[@]}):${RESET}"
  for w in "${WARNINGS[@]}"; do echo "    • $w"; done
fi

if ! $DRY_RUN; then
  echo -e "\n${CYAN}📁 Backups saved to: ${BACKUP_DIR}${RESET}"
fi

echo -e "\n${YELLOW}⚡ A reboot is recommended to apply all changes fully.${RESET}\n"
